name: Build and Push Image to ECR (from JSON)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  credecncials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/checkout@v4

      - name: Parse scraper config (Python)
        id: config
        run: |
          python scripts/parse_json.py config/scraper.json >> "$GITHUB_OUTPUT"

      - name: Show parsed values
        run: |
          echo "name: ${{ steps.config.outputs.name }}"
          echo "env: ${{ steps.config.outputs.env }}"
          echo "description: ${{ steps.config.outputs.description }}"
          echo "repository: ${{ steps.config.outputs.repository }}"
          echo "version: ${{ steps.config.outputs.version }}"

      - name: Ensure ECR repository exists
        shell: bash
        run: |
          ECR_REPO="${{ steps.config.outputs.repository }}"
          aws ecr describe-repositories --repository-names "$ECR_REPO" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "$ECR_REPO" >/dev/null

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check if image version already exists
        id: check_image
        shell: bash
        run: |
          REPO="${{ steps.config.outputs.repository }}"
          VERSION="${{ steps.config.outputs.version }}"

          echo "Checking if image exists: $REPO:$VERSION"

          if aws ecr describe-images \
              --repository-name "$REPO" \
              --image-ids imageTag="$VERSION" \
              >/dev/null 2>&1; then
            echo "Image already exists: $REPO:$VERSION"
            echo "image_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Image does not exist, continuing..."
            echo "image_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Image already exists — finishing
        if: steps.check_image.outputs.image_exists == 'true'
        run: |
          echo "La imagen ya existe en ECR. Finalizando."
          echo "Repo: ${{ steps.config.outputs.repository }}"
          echo "Version: ${{ steps.config.outputs.version }}"

      - name: Build and push image (Docker Action)
        if: steps.check_image.outputs.image_exists == 'false'
        uses: docker/build-push-action@v6
        env:
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.config.outputs.repository }}
        with:
          context: ./lambda
          push: true
          tags: |
            ${{ env.IMAGE_URI }}:${{ steps.config.outputs.version }}
            ${{ env.IMAGE_URI }}:${{ github.sha }}
            ${{ env.IMAGE_URI }}:latest

      - name: Output published image
        if: steps.check_image.outputs.image_exists == 'false'
        shell: bash
        run: |
          echo "Pushed:"
          echo "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.config.outputs.repository }}:${{ steps.config.outputs.version }}"
          echo "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.config.outputs.repository }}:${{ github.sha }}"
          echo "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.config.outputs.repository }}:latest"
      
      # -------------------------
      # Terraform (infra)
      # -------------------------
      - name: Setup Teerraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init (S3 backend)
        working-directory: infra
        run: terraform init

      - name: Terraform apply (Lambda + SFN + Scheduler)
        working-directory: infra
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="ecr_repo=${{ steps.config.outputs.repository }}" \
            -var="image_tag=${{ steps.config.outputs.version }}" \
            -var="lambda_name=${{ steps.config.outputs.lambda_name }}" \
            -var="state_machine_name=${{ steps.config.outputs.state_machine_name }}" \
            -var="schedule_name=${{ steps.config.outputs.schedule_name }}" \
            -var="schedule_expression=${{ steps.config.outputs.schedule_expression }}" \
            -var="lambda_exec_role_arn=${{ secrets.DEV_LAMBDA_EXEC_ROLE_ARN }}" \
            -var="sfn_role_arn=${{ secrets.DEV_SFN_ROLE_ARN }}" \
            -var="scheduler_role_arn=${{ secrets.DEV_SCHEDULER_ROLE_ARN }}"